2019-03-27 11:59:36,707[yyyy-MM-dd HH:mm:ss] - 0 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Exception: 
com.capgemini.bankapp.exceptions.LowBalanceException: account balance not sufficient..
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:42)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:77)
2019-03-27 12:02:25,509[yyyy-MM-dd HH:mm:ss] - 1 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - withdraw failed: 
com.capgemini.bankapp.exceptions.LowBalanceException: account balance not sufficient..
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:42)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:77)
2019-03-27 12:03:59,013[yyyy-MM-dd HH:mm:ss] - 93505 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - withdraw failed: 
com.capgemini.bankapp.exceptions.LowBalanceException: account balance not sufficient..
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:42)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:77)
2019-03-28 10:45:47,307[yyyy-MM-dd HH:mm:ss] - 0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4526)
	at com.capgemini.bankapp.util.DbUtil.rollback(DbUtil.java:58)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:79)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:104)
2019-03-28 10:54:40,788[yyyy-MM-dd HH:mm:ss] - 1 - [main] ERROR com.capgemini.bankapp.service.impl.BankAccountServiceImpl  - Exception 
com.capgemini.bankapp.exceptions.AccountNotFoundException: BankAccount doesnt exists...
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:55)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:79)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:104)
2019-03-28 10:54:40,795[yyyy-MM-dd HH:mm:ss] - 8 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4526)
	at com.capgemini.bankapp.util.DbUtil.rollback(DbUtil.java:58)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:83)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:104)
2019-03-28 11:58:31,190[yyyy-MM-dd HH:mm:ss] - 1 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:49)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:44)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:77)
2019-03-28 18:11:48,001[yyyy-MM-dd HH:mm:ss] - 1 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:49)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:44)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:77)
